<a href="https://colab.research.google.com/github/MarcelaMonteiroMontenegroGallo/Python/blob/master/Absenteeism_at_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install scikit-learn

In [0]:
from google.colab import files
uploaded = files.upload()

Saving Absenteeism-data.csv to Absenteeism-data.csv


In [111]:
import pandas as pd
import matplotlib.pyplot as plt

raw_csv_data = pd.read_csv('Absenteeism-data.csv')
raw_csv_data.shape

(700, 12)

# PRE PROCESSAMENTO

In [0]:
df = raw_csv_data.copy()

In [0]:
pd.options.display.max_rows = None
pd.options.display.max_columns = None

In [0]:
df

In [0]:
df.info()

DROP


In [0]:
df.drop(['ID'], axis=1)

In [0]:
df_no_age = df.drop(['Age'], axis= 1)
df_no_age

In [0]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [0]:
len(df['Reason for Absence'].unique())

28


get_dummies

In [0]:
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first= True)
reason_columns

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3     0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
5     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
6     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
7     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
8     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
9     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
10    1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
11    1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
12    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
13    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
14    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
15    0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   
16    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
17    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
18    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
19    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
20    0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   
21    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
22    0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   
23    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
24    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
25    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
26    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
27    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
28    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
29    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
30    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
31    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
32    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
33    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
34    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
35    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
36    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
37    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
38    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
39    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
40    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
41    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
42    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
43    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
44    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
45    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
46    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
47    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
48    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
49    0   0   0   0   0   0   0   0   0   0   0   0   0

In [112]:
reason_columns

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3     0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
5     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
6     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
7     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
8     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
9     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
10    1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
11    1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
12    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
13    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
14    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
15    0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   
16    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
17    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
18    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
19    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
20    0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   
21    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
22    0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   
23    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
24    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
25    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
26    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
27    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
28    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
29    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
30    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
31    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
32    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
33    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   
34    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
35    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
36    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
37    0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
38    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
39    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
40    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
41    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
42    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
43    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
44    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
45    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
46    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
47    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
48    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
49    0   0   0   0   0   0   0   0   0   0   0   0   0

In [0]:
df.columns.values

array(['ID', 'Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [0]:
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)

In [0]:
df = pd.concat([df, reason_type_1,reason_type_2,reason_type_3,reason_type_4], axis =1)
df

In [0]:
df= df.drop(['ID'], axis= 1)

In [0]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours', 0, 1, 2, 3], dtype=object)

In [0]:
columns_names = ['Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours', 'Reason_1','Reason_2', 'Reason_3','Reason_4']

In [0]:
df= df.drop(['Reason for Absence'], axis= 1)

In [0]:
df

In [0]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [0]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours','Reason_1','Reason_2' , 'Reason_3', 'Reason_4']

In [0]:
df.columns = column_names

In [114]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [0]:
column_names_reodered = ['Reason_1','Reason_2' , 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [0]:
df = df[column_names_reodered]

In [115]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

Create a Checkpoint  

In [0]:
df_reason_mod = df.copy()

In [0]:
df_reason_mod

DATE


In [125]:
type(df_reason_mod['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [0]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'] , format = '%d/%m/%Y')

In [124]:
df_reason_mod['Date'] 

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
5     2015-07-10
6     2015-07-17
7     2015-07-24
8     2015-07-06
9     2015-07-13
10    2015-07-20
11    2015-07-14
12    2015-07-15
13    2015-07-15
14    2015-07-15
15    2015-07-17
16    2015-07-17
17    2015-07-27
18    2015-07-30
19    2015-08-05
20    2015-08-12
21    2015-08-03
22    2015-08-10
23    2015-08-14
24    2015-08-17
25    2015-08-24
26    2015-08-04
27    2015-08-12
28    2015-08-19
29    2015-08-28
30    2015-08-17
31    2015-08-27
32    2015-08-27
33    2015-08-17
34    2015-08-17
35    2015-08-17
36    2015-08-04
37    2015-08-20
38    2015-08-21
39    2015-08-28
40    2015-09-01
41    2015-09-07
42    2015-09-01
43    2015-09-08
44    2015-09-09
45    2015-09-13
46    2015-09-14
47    2015-09-24
48    2015-09-04
49    2015-09-14
50    2015-09-21
51    2015-09-28
52    2015-09-08
53    2015-09-15
54    2015-09-22
55    2015-09-29
56    2015-09-16
57    2015-09-23
58    2015-09-

In [126]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
Reason_1                     700 non-null uint8
Reason_2                     700 non-null uint8
Reason_3                     700 non-null uint8
Reason_4                     700 non-null uint8
Date                         700 non-null datetime64[ns]
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(8), uint8(4)
memory usage: 57.5 KB


Extract The Month Value

In [132]:
df_reason_mod['Date'][699].month

5

In [133]:
list_months =[]
list_months

[]

In [0]:
for i in range(700):
    list_months.append(df_reason_mod['Date'][i].month)

In [0]:
list_months

In [139]:
len(list_months)

700

In [0]:
df_reason_mod['Month Value'] = list_months

In [141]:
df_reason_mod .head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  
0         2     1                          4            7  
1         1     0                          0            7  
2         0     0                          2            7  
3         2     0                          4            7  
4         2     1                          2            7

Extract the day of the Week 


In [142]:
df_reason_mod['Date'][0].weekday()

1

In [0]:
def date_to_weekdaay(date_value):
    return date_value.weekday()

In [0]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(date_to_weekdaay) 

In [147]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

Create checkpoint

In [0]:
df_reason_date_mod = df_reason_mod.copy()

In [0]:
df_reason_date_mod['Education']= df_reason_date_mod['Education'].map({1:0 , 2:1 , 3:1, 4:1})

In [151]:
df_reason_date_mod['Education'].unique()

array([0, 1])

In [152]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [153]:
df_preprocessed = df_reason_mod.copy()
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

 **Creating a logistic relevant libraries**  
 






In [0]:
import numpy as np

In [159]:
df_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [160]:
targets =np.where(df_preprocessed['Absenteeism Time in Hours'] > 3 , 1 , 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [0]:
df_preprocessed = df_preprocessed.drop(['Date'], axis= 1)

In [184]:
df_preprocessed['Excessive Absenteeisn'] = targets
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeisn  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [185]:
targets.sum()/ targets.shape[0]

0.45571428571428574

In [0]:
data_with_targets = df_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [187]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
5           0         0         0         1                     179   
6           0         0         0         1                     361   
7           0         0         0         1                     260   
8           0         0         1         0                     155   
9           0         0         0         1                     235   
10          1         0         0         0                     260   
11          1         0         0         0                     260   
12          1         0         0         0                     260   
13          1         0         0         0                     179   
14          0         0         0         1                     179   
15          1         0         0         0                     246   
16          0         0         0         1                     179   
17          0         0         1         0                     179   
18          1         0         0         0                     189   
19          0         0         0         1                     248   
20          1         0         0         0                     330   
21          1         0         0         0                     179   
22          1         0         0         0                     361   
23          0         0         0         1                     260   
24          0         0         1         0                     289   
25          0         0         0         1                     361   
26          0         0         0         1                     289   
27          0         0         0         1                     157   
28          0         0         1         0                     289   
29          0         0         0         1                     179   
30          0         0         1         0                     179   
31          0         0         1         0                     235   
32          0         0         0         1                     235   
33          0         0         1         0                     235   
34          0         0         0         1                     179   
35          0         0         0         1                     361   
36          0         0         0         1                     289   
37          1         0         0         0                     291   
38          0         0         0         1                     235   
39          0         0         0         1                     260   
40          0         0         0         1                     184   
41          0         0         0         1                     118   
42          0         0         0         1                     179   
43          0         0         1         0                     235   
44          0         0         0         1                     155   
45          0         0         0         1                     118   
46          0         0         0         1                     179   
47          0         0         0         1                     291   
48          0         0         0         1                     260   
49          1         0         0         0                     291   
50          0         0         0         0                     260   
51          0         0         0         0                     225   
52          0         0         0         1                     225   
53          0         0         0         1                     118   
54          0         0         0         0                     289   
55          0         0      

In [0]:
unscaled_inputs =data_with_targets.iloc[:,:-1]

In [189]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
5           0         0         0         1                     179   
6           0         0         0         1                     361   
7           0         0         0         1                     260   
8           0         0         1         0                     155   
9           0         0         0         1                     235   
10          1         0         0         0                     260   
11          1         0         0         0                     260   
12          1         0         0         0                     260   
13          1         0         0         0                     179   
14          0         0         0         1                     179   
15          1         0         0         0                     246   
16          0         0         0         1                     179   
17          0         0         1         0                     179   
18          1         0         0         0                     189   
19          0         0         0         1                     248   
20          1         0         0         0                     330   
21          1         0         0         0                     179   
22          1         0         0         0                     361   
23          0         0         0         1                     260   
24          0         0         1         0                     289   
25          0         0         0         1                     361   
26          0         0         0         1                     289   
27          0         0         0         1                     157   
28          0         0         1         0                     289   
29          0         0         0         1                     179   
30          0         0         1         0                     179   
31          0         0         1         0                     235   
32          0         0         0         1                     235   
33          0         0         1         0                     235   
34          0         0         0         1                     179   
35          0         0         0         1                     361   
36          0         0         0         1                     289   
37          1         0         0         0                     291   
38          0         0         0         1                     235   
39          0         0         0         1                     260   
40          0         0         0         1                     184   
41          0         0         0         1                     118   
42          0         0         0         1                     179   
43          0         0         1         0                     235   
44          0         0         0         1                     155   
45          0         0         0         1                     118   
46          0         0         0         1                     179   
47          0         0         0         1                     291   
48          0         0         0         1                     260   
49          1         0         0         0                     291   
50          0         0         0         0                     260   
51          0         0         0         0                     225   
52          0         0         0         1                     225   
53          0         0         0         1                     118   
54          0         0         0         0                     289   
55          0         0      

**Standardize the data**

In [0]:
from sklearn.preprocessing import StandardScaler
absenteeisn_scaler = StandardScaler()

In [192]:
absenteeisn_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [193]:
scaled_inputs = absenteeisn_scaler.transform(unscaled_inputs)
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.00772546],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
        -0.3882935 ,  0.66825259]])

In [194]:
scaled_inputs.shape

(700, 14)

**Split the data Into train & test and shuffle**


In [0]:
from sklearn.model_selection import train_test_split 

Split

In [197]:
train_test_split(scaled_inputs , targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.3882935 , -1.35968157],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.10278357, -0.68370352],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
          0.18272635, -0.00772546],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ...,  0.26848661,
         -0.3882935 , -0.00772546],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
          1.03925612,  0.66825259],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
         -0.67380342, -1.35968157]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -1.53033319,  1.34423065],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -1.24482327,  0.66825259],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.95931334, -1.35968157],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  

In [0]:
x_train , x_test , y_train , y_test = train_test_split(scaled_inputs , targets, train_size = 0.8)

In [208]:
print(x_train.shape , y_train.shape)

(560, 14) (560,)


In [209]:
print(x_test.shape , y_test.shape)

(140, 14) (140,)


**Logistic regression with skelearn**


In [0]:
from sklearn.linear_model import LogisticRegression

Training the model


In [0]:
reg = LogisticRegression()

In [215]:
reg.fit(x_train , y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [217]:
reg.score(x_train , y_train)

0.7767857142857143

**Manually check the accuracy**


In [218]:
model_outputs = reg.predict(x_train)
model_outputs


array([1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,

In [219]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,

In [0]:
model_outputs == y_train

In [221]:
np.sum(model_outputs == y_train)

435

In [222]:
reg.score(x_train , y_train)

0.7767857142857143

**Finding the intercept and coefficients**

In [223]:
reg.intercept_

array([-0.21368533])

In [224]:
reg.coef_

array([[ 2.10882291,  0.32710987,  1.58528192,  1.48928341,  0.81501543,
        -0.11169616, -0.28490062,  0.10311468,  0.29999675,  0.00859262,
         0.44281158, -0.35981934,  0.13724642, -0.2196186 ]])

In [227]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [0]:
feature_name = unscaled_inputs.columns.values

In [230]:
summary_table = pd.DataFrame(columns = ['Feature name'], data= feature_name) 
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table 

Feature name  Coefficient
0                  Reason_1     2.108823
1                  Reason_2     0.327110
2                  Reason_3     1.585282
3                  Reason_4     1.489283
4    Transportation Expense     0.815015
5          Distance to Work    -0.111696
6                       Age    -0.284901
7   Daily Work Load Average     0.103115
8           Body Mass Index     0.299997
9                 Education     0.008593
10                 Children     0.442812
11                     Pets    -0.359819
12              Month Value     0.137246
13          Day of the Week    -0.219619

In [232]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.213685
2                  Reason_1     2.108823
3                  Reason_2     0.327110
4                  Reason_3     1.585282
5                  Reason_4     1.489283
6    Transportation Expense     0.815015
7          Distance to Work    -0.111696
8                       Age    -0.284901
9   Daily Work Load Average     0.103115
10          Body Mass Index     0.299997
11                Education     0.008593
12                 Children     0.442812
13                     Pets    -0.359819
14              Month Value     0.137246
15          Day of the Week    -0.219619